// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.1
// source: src/grpc/hotel.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hotel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HotelID     int32  `protobuf:"varint,1,opt,name=hotelID,proto3" json:"hotelID,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rating      int32  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Country     string `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	RoomAvaible int32  `protobuf:"varint,6,opt,name=room_avaible,json=roomAvaible,proto3" json:"room_avaible,omitempty"`
	Price       int32  `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	Address     string `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *Hotel) Reset() {
	*x = Hotel{}
	mi := &file_src_grpc_hotel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hotel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hotel) ProtoMessage() {}

func (x *Hotel) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_hotel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hotel.ProtoReflect.Descriptor instead.
func (*Hotel) Descriptor() ([]byte, []int) {
	return file_src_grpc_hotel_proto_rawDescGZIP(), []int{0}
}

func (x *Hotel) GetHotelID() int32 {
	if x != nil {
		return x.HotelID
	}
	return 0
}

func (x *Hotel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hotel) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Hotel) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Hotel) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Hotel) GetRoomAvaible() int32 {
	if x != nil {
		return x.RoomAvaible
	}
	return 0
}

func (x *Hotel) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Hotel) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetHotelsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetHotelsRequest) Reset() {
	*x = GetHotelsRequest{}
	mi := &file_src_grpc_hotel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotelsRequest) ProtoMessage() {}

func (x *GetHotelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_hotel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotelsRequest.ProtoReflect.Descriptor instead.
func (*GetHotelsRequest) Descriptor() ([]byte, []int) {
	return file_src_grpc_hotel_proto_rawDescGZIP(), []int{1}
}

type GetHotelsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hotel *Hotel `protobuf:"bytes,1,opt,name=hotel,proto3" json:"hotel,omitempty"`
}

func (x *GetHotelsResponse) Reset() {
	*x = GetHotelsResponse{}
	mi := &file_src_grpc_hotel_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotelsResponse) ProtoMessage() {}

func (x *GetHotelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_hotel_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotelsResponse.ProtoReflect.Descriptor instead.
func (*GetHotelsResponse) Descriptor() ([]byte, []int) {
	return file_src_grpc_hotel_proto_rawDescGZIP(), []int{2}
}

func (x *GetHotelsResponse) GetHotel() *Hotel {
	if x != nil {
		return x.Hotel
	}
	return nil
}

type GetHotelByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetHotelByIDRequest) Reset() {
	*x = GetHotelByIDRequest{}
	mi := &file_src_grpc_hotel_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotelByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotelByIDRequest) ProtoMessage() {}

func (x *GetHotelByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_hotel_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotelByIDRequest.ProtoReflect.Descriptor instead.
func (*GetHotelByIDRequest) Descriptor() ([]byte, []int) {
	return file_src_grpc_hotel_proto_rawDescGZIP(), []int{3}
}

func (x *GetHotelByIDRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetHotelByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hotel *Hotel `protobuf:"bytes,1,opt,name=hotel,proto3" json:"hotel,omitempty"`
}

func (x *GetHotelByIDResponse) Reset() {
	*x = GetHotelByIDResponse{}
	mi := &file_src_grpc_hotel_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHotelByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHotelByIDResponse) ProtoMessage() {}

func (x *GetHotelByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_grpc_hotel_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHotelByIDResponse.ProtoReflect.Descriptor instead.
func (*GetHotelByIDResponse) Descriptor() ([]byte, []int) {
	return file_src_grpc_hotel_proto_rawDescGZIP(), []int{4}
}

func (x *GetHotelByIDResponse) GetHotel() *Hotel {
	if x != nil {
		return x.Hotel
	}
	return nil
}

var File_src_grpc_hotel_proto protoreflect.FileDescriptor

var file_src_grpc_hotel_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x72, 0x63, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x68, 0x6f, 0x74, 0x65, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0xdc, 0x01, 0x0a,
	0x05, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x49, 0x44,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x6f, 0x6f, 0x6d,
	0x5f, 0x61, 0x76, 0x61, 0x69, 0x62, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x72, 0x6f, 0x6f, 0x6d, 0x41, 0x76, 0x61, 0x69, 0x62, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x12, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x36, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x48, 0x6f, 0x74, 0x65, 0x6c,
	0x52, 0x05, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x22, 0x25, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x48, 0x6f,
	0x74, 0x65, 0x6c, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x22, 0x39,
	0x0a, 0x14, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x48, 0x6f, 0x74,
	0x65, 0x6c, 0x52, 0x05, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x32, 0x95, 0x01, 0x0a, 0x0c, 0x48, 0x6f,
	0x74, 0x65, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x47, 0x65,
	0x74, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47,
	0x65, 0x74, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12, 0x45, 0x0a, 0x0c, 0x47, 0x65,
	0x74, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x42, 0x79, 0x49, 0x44, 0x12, 0x19, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x6f, 0x74, 0x65, 0x6c, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74,
	0x48, 0x6f, 0x74, 0x65, 0x6c, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x26, 0x5a, 0x24, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2d, 0x73, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x73, 0x72, 0x63, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x3b, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_src_grpc_hotel_proto_rawDescOnce sync.Once
	file_src_grpc_hotel_proto_rawDescData = file_src_grpc_hotel_proto_rawDesc
)

func file_src_grpc_hotel_proto_rawDescGZIP() []byte {
	file_src_grpc_hotel_proto_rawDescOnce.Do(func() {
		file_src_grpc_hotel_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_grpc_hotel_proto_rawDescData)
	})
	return file_src_grpc_hotel_proto_rawDescData
}

var file_src_grpc_hotel_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_src_grpc_hotel_proto_goTypes = []any{
	(*Hotel)(nil),                // 0: grpc.Hotel
	(*GetHotelsRequest)(nil),     // 1: grpc.GetHotelsRequest
	(*GetHotelsResponse)(nil),    // 2: grpc.GetHotelsResponse
	(*GetHotelByIDRequest)(nil),  // 3: grpc.GetHotelByIDRequest
	(*GetHotelByIDResponse)(nil), // 4: grpc.GetHotelByIDResponse
}
var file_src_grpc_hotel_proto_depIdxs = []int32{
	0, // 0: grpc.GetHotelsResponse.hotel:type_name -> grpc.Hotel
	0, // 1: grpc.GetHotelByIDResponse.hotel:type_name -> grpc.Hotel
	1, // 2: grpc.HotelService.GetHotels:input_type -> grpc.GetHotelsRequest
	3, // 3: grpc.HotelService.GetHotelByID:input_type -> grpc.GetHotelByIDRequest
	2, // 4: grpc.HotelService.GetHotels:output_type -> grpc.GetHotelsResponse
	4, // 5: grpc.HotelService.GetHotelByID:output_type -> grpc.GetHotelByIDResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_src_grpc_hotel_proto_init() }
func file_src_grpc_hotel_proto_init() {
	if File_src_grpc_hotel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_grpc_hotel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_grpc_hotel_proto_goTypes,
		DependencyIndexes: file_src_grpc_hotel_proto_depIdxs,
		MessageInfos:      file_src_grpc_hotel_proto_msgTypes,
	}.Build()
	File_src_grpc_hotel_proto = out.File
	file_src_grpc_hotel_proto_rawDesc = nil
	file_src_grpc_hotel_proto_goTypes = nil
	file_src_grpc_hotel_proto_depIdxs = nil
}
