services:
  hotel-svc:
    build:
      context: .
      dockerfile: src/hotel-svc/Dockerfile
    ports:
      - 9090:9090
      - 50051:50051
    env_file:
      - ./src/hotel-svc/.env
    depends_on:
      - hotel-db

  hotel-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASS}
      POSTGRES_DB: ${HOTEL_DB}
    ports:
      - 5432:5432
    volumes:
      - hotel-db-data:/var/lib/postgresql/data

  booking-svc:
    build:
      context: .
      dockerfile: src/booking-svc/Dockerfile
    ports:
      - 9091:9091
      - 50051:50051
    env_file:
      - ./src/booking-svc/.env
    depends_on:
      - booking-db
      - kafka
      - hotel-svc

  booking-db:
    image: postgres:latest
    env_file:
      - ./src/booking-svc/.env
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASS}
      POSTGRES_DB: ${BOOKING_DB}
    ports:
      - 5432:5432
    volumes:
      - booking-db-data:/var/lib/postgresql/data

  notification-svc:
    build:
      context: .
      dockerfile: src/notification-svc/Dockerfile
    ports:
      - 9092:9092
    depends_on:
      - kafka

  zookeeper:
    image: bitnami/zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: bitnami/kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092
    depends_on:
      - zookeeper

volumes:
  hotel-db-data:
  booking-db-data:

networks:
  default:
    driver: bridge